"""
TersoffForge: A LAMMPS Potential Builder
----------------------------------------
Author: Soheil Solhjoo - s.solhjoo@rug.nl
Date: 1-March-2026
Affilliation: ESD-ENTEG-FSE-University of Groningen

Description:
This script (TersoffForge) generates a LAMMPS-compatible .tersoff potential file
from a JSON configuration. It automates N^3 triplet generation and applies
specific mixing and zeroing rules as follows:

Mixing Rules:
- Arithmetic Mean: Exponents (lambda1, lambda2).
- Geometric Mean: Energy and cutoff parameters (A, B, R, S).
- B Scaling: B is scaled by the corresponding mix-Chi value (defaults to 1.0).

Technical Logic:
- Triplet generation is driven by the 'elements' list in the JSON.
- Angular (c, d, h) and exponents (m, gamma, lambda3) are from the central atom i.
- Mixed n and beta are inherited from the central atom i.
- Parameter Zeroing: n, beta, lambda1, lambda2, and A are set to 0.0 if j != k.
- Cutoff Conversion: LAMMPS R and D are calculated from R and S as:
    R_lammps = (R + S) / 2
    D_lammps = (S - R) / 2
"""

import json
import sys
import os
import math

# Project Metadata
TOOL_NAME = "TersoffForge"
AUTHOR_INFO = "Soheil Solhjoo - s.solhjoo@rug.nl"

def generate_tersoff_file(data, output_filename):
    """
    Core function to process parameters and write the .tersoff file.
    """
    elements = data.get("elements", [])
    params = data.get("parameters", {})
    mix_chi = data.get("mix-Chi", {})
    reference = data.get("reference", "No reference provided.")
    
    # Header construction
    header =  f"# LAMMPS Tersoff potential file\n"
    header += f"# Generated by: {TOOL_NAME} (Python script by {AUTHOR_INFO})\n"
    header += f"# Reference: {reference}\n"
    header += "# Element1 Element2 Element3 m gamma lambda3 c d h n beta lambda2 B R D lambda1 A\n"
    
    lines = []
    
    # Generate triplets based on the 'elements' subset defined in JSON
    for i in elements:
        for j in elements:
            for k in elements:
                # 1. Parameter Lookup
                try:
                    p_i = params[i]
                    p_j = params[j]
                except KeyError as e:
                    print(f"Error: Parameter set for element {e} not found in 'parameters' dictionary.")
                    sys.exit(1)
                
                # 2. Central Atom Properties (i)
                m = p_i['m']
                gamma = p_i['gamma']
                lambda3 = p_i['lambda3']
                c = p_i['c']
                d = p_i['d']
                h = p_i['h']
                
                # 3. Cutoff Mixing (i-j Bond)
                if i == j:
                    R_bond = p_i['R']
                    S_bond = p_i['S']
                else:
                    # Geometric mean for cutoffs
                    R_bond = math.sqrt(p_i['R'] * p_j['R'])
                    S_bond = math.sqrt(p_i['S'] * p_j['S'])
                
                # 4. Bond Order Scaling (B)
                # B is always calculated and scaled based on the i-j bond type
                if i == j:
                    B_base = p_i['B']
                    chi_key = f"{i}-{i}"
                    chi = mix_chi.get(chi_key, 1.0)
                else:
                    # Geometric mean for B
                    B_base = math.sqrt(p_i['B'] * p_j['B'])
                    # Symmetric lookup (checks i-j and j-i)
                    chi_key = f"{i}-{j}"
                    rev_chi_key = f"{j}-{i}"
                    chi = mix_chi.get(chi_key, mix_chi.get(rev_chi_key, 1.0))
                B = B_base * chi

                # 5. Bond Parameter Zeroing (n, beta, lambda1, lambda2, A)
                # Convention: Zeroed if the neighbors are different (j != k)
                if j != k:
                    n = 0.0
                    beta = 0.0
                    lambda1 = 0.0
                    lambda2 = 0.0
                    A = 0.0
                else:
                    # Case where j == k (AAA, BBB, ABB, BAA types)
                    n = p_i['n']
                    beta = p_i['beta']
                    
                    if i == j:
                        # Pure bonds (AAA, BBB)
                        lambda1 = p_i['lambda1']
                        lambda2 = p_i['lambda2']
                        A = p_i['A']
                    else:
                        # Mixed bonds (ABB, BAA)
                        # Arithmetic mean for exponents
                        lambda1 = (p_i['lambda1'] + p_j['lambda1']) / 2.0
                        lambda2 = (p_i['lambda2'] + p_j['lambda2']) / 2.0
                        # Geometric mean for energy parameter A
                        A = math.sqrt(p_i['A'] * p_j['A'])

                # 6. R/D Conversion for LAMMPS Format
                R_lammps = (R_bond + S_bond) / 2.0
                D_lammps = (S_bond - R_bond) / 2.0

                # 7. Format the triplet entry
                line = f"{i:<3} {j:<3} {k:<3} "
                line += f"{m:g} {gamma:g} {lambda3:g} "
                line += f"{c:g} {d:g} {h:g} "
                line += f"{n:g} {beta:g} "
                line += f"{lambda2:g} {B:g} "
                line += f"{R_lammps:g} {D_lammps:g} "
                line += f"{lambda1:g} {A:g}"
                lines.append(line)

    # Output to file
    try:
        with open(output_filename, 'w') as f:
            f.write(header)
            f.write("\n".join(lines))
            f.write("\n")
        print(f"Successfully created: {output_filename}")
    except IOError as e:
        print(f"Error writing to file: {e}")

def main():
    if len(sys.argv) < 2:
        print(f"Usage: python tersoff_builder.py <params.json> [output.tersoff]")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "potential.tersoff"

    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found.")
        sys.exit(1)

    try:
        with open(input_file, 'r') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON configuration: {e}")
        sys.exit(1)

    generate_tersoff_file(data, output_file)

if __name__ == "__main__":
    main()
